# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busines',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
